{% set version = "1.0.9" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-squash
  version: {{ version|replace("-", "_") }}

source:
  fn: squash_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/squash_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/squash/squash_{{ version }}.tar.gz

  sha256: ff381c85071e3407574e3db28d789657f64e7d3f9d74ac123539de22ab8ac6f4

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('squash')"  # [not win]
    - "\"%R%\" -e \"library('squash')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/squash/index.html
  license: Artistic-2.0
  summary: Functions for color-based visualization of multivariate data, i.e. colorgrams or heatmaps.  Lower-level
    functions  map numeric values to colors, display a matrix as an array of colors,
    and draw color keys.  Higher-level plotting functions generate a bivariate histogram,
    a dendrogram aligned with a color-coded matrix, a triangular distance matrix, and
    more.
  license_family: OTHER
extra:
   recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
