appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: dUPMu+JSOCmP0XElu/2gjL881SCKg0oOyAL1Bcmbjs8ZwvmW5I71wkAdnUc3pz/8ttfeSRtdQ9eqkr+ZHUbuAVWaSDOhNZPRigjWf7O1efdMdGTEJUxFi32eczOAtKLaz4s/GaLh/Fox4DSXx6o2S7zV3P62nujyprZteZsJI48j+eCvCopEDzwB1x/sOdFCfmY56L07kPDHzy8NhmTOSSVH6UV67lyqBge/3YrxjyKhX87BSK3g38msBxWz/cqxJCM2Sx6RmcOMD6DF4kOPVV07Aatr3FH/Fo2FfBHA5Vt0N07LALMIVgkcjUyFwi95Kwl0SaRYVSewq+iCRFFgseQDAUhKfA/Jys7BQb4fxoizj00aXiB83luSS33Dz2BSu5QTLztmhbBdi1/q8VGbx7GHN2xsrpvquwqm6a1D/7Fs+NFegr63mhQgP3DCGxSdXnx0m3Q8KnqV/zNiA3Q1MBTriMkoHP2iEJxEzcztHTRzve+4KHNcu0wmjyVV6p8Y7Ya/2XnGDSn8mCld18Pjp6UlIl66qkqd9T2kj5sjGmk+qXkTqaBT/4Y0BS3lfMWnFf0owmBEdWIJ7mnO92rqekP/8iI82k2+LKbr8y0DVWN927SgTL0vcKq3isQ4RLy3c9lsVncRyB5h5UzBMzKc2trWM/wE3usk6nu6qeQu7Hw=}
